<?xml version="1.0"?>
<robot name="roscontrol" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="width" value="0.2"/>
  <xacro:property name="length" value="0.4"/>
  <xacro:property name="height" value="0.1"/>
  <xacro:property name="wheeldia" value="0.15"/>
  <xacro:property name="spheredia" value="0.15"/>
  <xacro:property name="pi" value="3.1415"/>

  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>

  <material name="red">
    <color rgba="1 0 0 1"/>
  </material>

  <xacro:macro name="robot_inertia" params="mass">
    <inertial>
      <mass value="${mass}"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </xacro:macro>

  <link name="chasis">
    <visual>
      <geometry>
        <box size="${width} ${length} ${height}"/>
      </geometry>
    </visual>
    <xacro:robot_inertia mass="10"/>
  </link>

  <link name="left_wheel_back">
    <visual>
      <geometry>
        <cylinder length="${length/8}" radius="${wheeldia/2}"/>
      </geometry>
      <origin rpy="0 ${pi/2} 0" xyz="+0.15 0 0 "/>
      <material name="blue"/>
    </visual> 
    <collision>
      <geometry>
        <cylinder length="${length/8}" radius="${wheeldia/2}"/>
      </geometry>
      <origin rpy="0 ${pi/2} 0" xyz="+0.15 0 0 "/>
    </collision>
    <xacro:robot_inertia mass="2"/>   
  </link>

  <joint name="chasis_left_wheel_back" type="continuous">
    <parent link="chasis"/>
    <child link="left_wheel_back"/>
    <origin xyz="0 -0.15 0"/>
    <limit effort="30" velocity="2.0"/>
  </joint> 

  <transmission name="back_left_wheel_rotation">
    <type>transmission_interface/SimpleTransmission</type>
      <actuator name="back_left_wheel_motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
      <joint name="chasis_left_wheel_back">
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
      </joint>
  </transmission>

  <gazebo reference="back_left_wheel_motor">
    <mu1 value="200.0"/>
    <mu2 value="100.0"/>
    <kp value="10000000.0" />
    <kd value="1.0" />
    <material>Gazebo/Blue</material>
  </gazebo>

  <link name="right_wheel_front">
    <visual>
      <geometry>
        <cylinder length="${length/8}" radius="${wheeldia/2}"/>
      </geometry>
      <origin rpy="0 ${pi/2} 0" xyz="-0.15 0 0 "/>
      <material name="blue"/>
    </visual> 
    <collision>
      <geometry>
        <cylinder length="${length/8}" radius="${wheeldia/2}"/>
      </geometry>
      <origin rpy="0 ${pi/2} 0" xyz="-0.15 0 0 "/>
    </collision>
    <xacro:robot_inertia mass="2"/>   
  </link>

  <joint name="chasis_right_wheel_front" type="continuous">
    <parent link="chasis"/>
    <child link="right_wheel_front"/>
    <origin xyz="0 +0.15 0"/>
    <limit effort="30" velocity="2.0"/>
  </joint> 

  <transmission name="front_right_wheel_rotation">
    <type>transmission_interface/SimpleTransmission</type>
      <actuator name="front_right_wheel_motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
      <joint name="chasis_right_wheel_front">
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
      </joint>
  </transmission>

  <gazebo reference="front_right_wheel_motor">
    <mu1 value="200.0"/>
    <mu2 value="100.0"/>
    <kp value="10000000.0" />
    <kd value="1.0" />
    <material>Gazebo/Blue</material>
  </gazebo>
 

<!-- code for left wheel --> 
  <link name="right_wheel_back">
    <visual>
      <geometry>
        <cylinder length="${length/8}" radius="${wheeldia/2}"/>
      </geometry>
      <origin rpy="0 ${pi/2} 0" xyz="-0.15 0 0 "/>
      <material name="blue"/>
    </visual>  
    <collision>
      <geometry>
        <cylinder length="${length/8}" radius="${wheeldia/2}"/>
      </geometry>
      <origin rpy="0 ${pi/2} 0" xyz="-0.15 0 0 "/>
    </collision>
    <xacro:robot_inertia mass="2"/>   
  </link>
  <joint name="chasis_right_wheel_back" type="continuous">
    <parent link="chasis"/>
    <child link="right_wheel_back"/>
    <origin xyz="0 -0.15 0"/>
    <limit effort="30" velocity="2.0"/>
  </joint>

  <transmission name="back_right_wheel_rotation">
    <type>transmission_interface/SimpleTransmission</type>
      <actuator name="back_right_wheel_motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
      <joint name="chasis_right_wheel_back">
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
      </joint>
  </transmission>

  <gazebo reference="back_right_wheel_motor">
    <mu1 value="200.0"/>
    <mu2 value="100.0"/>
    <kp value="10000000.0" />
    <kd value="1.0" />
    <material>Gazebo/Blue</material>
  </gazebo>

  <link name="left_wheel_front">
    <visual>
      <geometry>
        <cylinder length="${length/8}" radius="${wheeldia/2}"/>
      </geometry>
      <origin rpy="0 ${pi/2} 0" xyz="+0.15 0 0 "/>
      <material name="blue"/>
    </visual> 
    <collision>
      <geometry>
        <cylinder length="${length/8}" radius="${wheeldia/2}"/>
      </geometry>
      <origin rpy="0 ${pi/2} 0" xyz="+0.15 0 0 "/>
    </collision>
    <xacro:robot_inertia mass="2"/>   
  </link>

  <joint name="chasis_left_wheel_front" type="continuous">
    <parent link="chasis"/>
    <child link="left_wheel_front"/>
    <origin xyz="0 +0.15 0"/>
    <limit effort="30" velocity="2.0"/>
  </joint> 

  <transmission name="front_right_wheel_rotation">
    <type>transmission_interface/SimpleTransmission</type>
      <actuator name="front_right_wheel_motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
      <joint name="chasis_left_wheel_front">
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
      </joint>
  </transmission>

  <gazebo reference="front_left_wheel_motor">
    <mu1 value="200.0"/>
    <mu2 value="100.0"/>
    <kp value="10000000.0" />
    <kd value="1.0" />
    <material>Gazebo/Blue</material>
  </gazebo>
 
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/</robotNamespace>
    </plugin>
  </gazebo>

</robot>








					

    
	
